-- Types
DROP TYPE IF EXISTS status_convenio_enum CASCADE;
CREATE TYPE status_convenio_enum AS ENUM ('Ativo', 'Inativo');

DROP TYPE IF EXISTS contract_status_enum CASCADE;
CREATE TYPE contract_status_enum AS ENUM ('Ativo', 'Encerrado');

-- Institutions
CREATE TABLE IF NOT EXISTS institutions (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social TEXT NOT NULL,
    cnpj TEXT NOT NULL UNIQUE,
    coordenador_responsavel TEXT,
    status_convenio status_convenio_enum DEFAULT 'Ativo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Students
CREATE TABLE IF NOT EXISTS students (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cpf TEXT NOT NULL UNIQUE,
    curso TEXT,
    semestre INTEGER,
    previsao_formatura DATE,
    dados_bancarios TEXT,
    comprovante_matricula_path TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Supervisors
CREATE TABLE IF NOT EXISTS supervisors (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    cargo TEXT,
    area TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Contracts
CREATE TABLE IF NOT EXISTS contracts (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id),
    institution_id INTEGER NOT NULL REFERENCES institutions(id),
    supervisor_id INTEGER NOT NULL REFERENCES supervisors(id),
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    valor_bolsa DECIMAL(10, 2),
    valor_transporte DECIMAL(10, 2),
    apolice_seguro TEXT,
    status contract_status_enum DEFAULT 'Ativo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- TimeSheets
CREATE TABLE IF NOT EXISTS timesheets (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id INTEGER NOT NULL REFERENCES contracts(id),
    date DATE NOT NULL,
    hora_entrada TIME,
    hora_saida TIME,
    geolocalizacao TEXT,
    is_dia_prova BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Evaluations
CREATE TABLE IF NOT EXISTS evaluations (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id INTEGER NOT NULL REFERENCES contracts(id),
    competencias_tecnicas TEXT,
    competencias_comportamentais TEXT,
    nota DECIMAL(5, 2),
    feedback_supervisor TEXT,
    feedback_estagiario TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Financials
CREATE TABLE IF NOT EXISTS financials (
    id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id INTEGER NOT NULL REFERENCES contracts(id),
    saldo_recesso DECIMAL(5, 2) DEFAULT 0.00,
    pagamentos_realizados DECIMAL(10, 2) DEFAULT 0.00,
    last_recesso_calc DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
