-- Gestão de Estagiários - MySQL Schema (Versão Otimizada)

-- 1. Tabelas de Domínio (Referência)
CREATE TABLE IF NOT EXISTS lotacoes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    subunidade VARCHAR(255),
    unidade VARCHAR(100),
    lotacao VARCHAR(100),
    municipio VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS niveis_escolaridade (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cargas_horarias (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(50) NOT NULL UNIQUE,
    horas_diarias INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS motivos_desligamento (
    id INT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Entidades Principais
CREATE TABLE IF NOT EXISTS institutions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    razao_social VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    nome_diretor VARCHAR(255) NULL,
    email_diretor VARCHAR(255) NULL,
    nome_coordenador VARCHAR(255) NULL,
    email_coordenador VARCHAR(255) NULL,
    status_convenio ENUM('Ativo', 'Inativo') DEFAULT 'Ativo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    curso VARCHAR(255),
    semestre INT,
    previsao_formatura DATE,
    nivel_escolaridade_id INT,
    institution_id INT,
    comprovante_matricula_path VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (nivel_escolaridade_id) REFERENCES niveis_escolaridade(id),
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supervisors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(255),
    email VARCHAR(255),
    telefone_ramal VARCHAR(50),
    lotacao_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lotacao_id) REFERENCES lotacoes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS positions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lotacao_id INT NOT NULL,
    nivel_escolaridade_id INT NOT NULL,
    carga_horaria_id INT NOT NULL,
    quantidade INT DEFAULT 1,
    remuneracao_base DECIMAL(10, 2),
    requisitos TEXT,
    status ENUM('Aberta', 'Ocupada', 'Suspensa') DEFAULT 'Aberta',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (lotacao_id) REFERENCES lotacoes(id) ON DELETE CASCADE,
    FOREIGN KEY (nivel_escolaridade_id) REFERENCES niveis_escolaridade(id),
    FOREIGN KEY (carga_horaria_id) REFERENCES cargas_horarias(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contracts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    student_id INT NOT NULL,
    institution_id INT NOT NULL,
    supervisor_id INT NOT NULL,
    position_id INT NOT NULL,
    carga_horaria_id INT NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    data_desligamento DATE NULL,
    motivo_desligamento_id INT NULL,
    valor_bolsa DECIMAL(10, 2),
    valor_transporte DECIMAL(10, 2),
    status ENUM('Ativo', 'Encerrado') DEFAULT 'Ativo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (institution_id) REFERENCES institutions(id) ON DELETE CASCADE,
    FOREIGN KEY (supervisor_id) REFERENCES supervisors(id) ON DELETE CASCADE,
    FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE,
    FOREIGN KEY (carga_horaria_id) REFERENCES cargas_horarias(id),
    FOREIGN KEY (motivo_desligamento_id) REFERENCES motivos_desligamento(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Tabelas de Acompanhamento
CREATE TABLE IF NOT EXISTS timesheets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contract_id INT NOT NULL,
    date DATE NOT NULL,
    hora_entrada TIME,
    hora_saida TIME,
    geolocalizacao VARCHAR(255),
    is_dia_prova BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS evaluations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contract_id INT NOT NULL,
    competencias_tecnicas TEXT,
    competencias_comportamentais TEXT,
    nota DECIMAL(5, 2),
    feedback_supervisor TEXT,
    feedback_estagiario TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS financials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contract_id INT NOT NULL,
    saldo_recesso DECIMAL(5, 2) DEFAULT 0.00,
    pagamentos_realizados DECIMAL(10, 2) DEFAULT 0.00,
    last_recesso_calc DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. Inserção de Dados Iniciais
INSERT INTO niveis_escolaridade (descricao) VALUES ('Médio'), ('Superior');
INSERT INTO cargas_horarias (descricao, horas_diarias) VALUES ('4 Horas', 4), ('6 Horas', 6);
INSERT INTO motivos_desligamento (descricao) VALUES 
('Fim do contrato'), 
('Rescisão antecipada pelo estagiário'), 
('Rescisão antecipada pela instituição'),
('Contratação efetiva'),
('Desempenho insuficiente');

-- Seed Data para Lotacoes
INSERT INTO lotacoes (id, subunidade, unidade, lotacao, municipio) VALUES
(1, 'COORDENACAO DE ASSUNTOS FAZ ESTRATEGICOS / CAFE', 'CAFE', 'OC', 'BELEM'),
(2, 'CELULA DE COMUNICACAO - CCOM / CAFE', 'CAFE', 'OC', 'BELEM'),
(3, 'CELULA DO LABORATÓRIO DE GESTÃO DO CONHECIMENTO CAFE', 'CAFE', 'OC', 'BELEM'),
(4, 'COORD EXEC DE CONTROLE DE MERCADORIAS EM TRANSITO', 'CECOMT', 'REG', 'BELEM'),
(5, 'UNID DE EXEC DE CONTR MERC EM TRANS ALCA VIARIA / CECOMT', 'CECOMT', 'REG', 'SAO FRANCISCO DO'),
(6, 'UNID DE EXEC DE CONTR MERC EM TRANS SAO FRANCISCO / CECOMT', 'CECOMT', 'REG', 'SAO FRANCISCO DO'),
(7, 'UNID DE EXEC DE CONTR MERC EM TRANS SAO FRANCISCO / CECOMT', 'CECOMT', 'REG', 'PRATINHA'),
(8, 'UNID DE EXEC DE CONTR MERC EM TRANS DO LITORAL / CECOMT', 'CECOMT', 'REG', 'BELEM'),
(9, 'UNID DE EXEC DE CONTR MERC EM TRANS DOS CORREIOS / CECOMT', 'CECOMT', 'REG', 'BELEM'),
(10, 'UNID DE EXEC DE CONTR MERC EM TRANS DA GRANDE BELEM / CECOMT', 'CECOMT', 'REG', 'BELEM'),
(11, 'UNID DE EXEC DE CONTR MERC EM TRANS ALCA VIARIA / CECOMT', 'CECOMT', 'REG', 'ACARA'),
(12, 'UNID DE EXEC DE CONTR MERC EM TRANS DA PRATINHA / CECOMT', 'CECOMT', 'REG', 'BELEM'),
(13, 'COORD EXEC DE CONTR DE MERC TRANS SERRA DO CACHIMBO', 'CECOMT DA SERRA DO CACHIMBO', 'REG', 'NOVO PROGRESSO'),
(14, 'UNID DE EXEC CONTR MERC TRANS DE SAO GERALDO DO ARAGUAIA / CECOMT DE CARAJAS', 'CECOMT DE CARAJAS', 'REG', 'SAO GERALDO DO ARAGUAIA'),
(15, 'COORD EXEC DE CONTR DE MERC EM TRANS DE CARAJAS', 'CECOMT DE CARAJAS', 'REG', 'MARABA'),
(16, 'UNID DE EXEC CONTR MERC TRANS DE JARBAS PASSARINHO / CECOMT DE CARAJAS', 'CECOMT DE CARAJAS', 'REG', 'BREJO GRANDE DO ARAGUAIA'),
(17, 'UNID DE EXEC CONTR MERC TRANS DE MARABA KM 09 / CECOMT DE CARAJAS', 'CECOMT DE CARAJAS', 'REG', 'MARABA'),
(18, 'UNID DE EXEC DE CONTR MERC EM TRANS VILA DO CONDE / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BARCARENA'),
(19, 'UNID DE EXEC DE CONTR MERC EM TRANS DE SANTAREM / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'CONCEICAO DO ARAGUAIA'),
(20, 'UNID DE EXEC DE CONTR MERC EM TRANS CAIS DO PORTO / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(21, 'COORD EXEC DE CONTR DE MERC TRANS DE PORTOS E AEROPORTOS', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(22, 'UNID DE EXEC DE CONTR MERC EM TRANS DE SANTAREM / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'SANTAREM'),
(23, 'COORD EXEC DE CONTR DE MERC TRANS DE PORTOS E AEROPORTOS', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'ABAETETUBA'),
(24, 'UNID DE EXEC DE CONTR MERC EM TRANS VILA DO CONDE / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(25, 'UNID DE EXEC DE CONTR MERC EM TRANS DO PORTO SECO / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(26, 'UNID DE EXEC DE CONTR MERC EM TRANS DO AEROPORTO / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(27, 'UNID DE EXEC DE CONTR MERC EM TRANS SÃO JOSE (PONTAO) / CECOMT DO ARAGUAIA', 'CECOMT DO ARAGUAIA', 'REG', 'XINGUARA'),
(28, 'UNID DE EXEC DE CONTR MERC EM TRANS DO ARAGUAIA / CECOMT DO ARAGUAIA', 'CECOMT DO ARAGUAIA', 'REG', 'CONCEICAO DO ARAGUAIA'),
(29, 'COORD EXEC DE CONTR DE MERC EM TRANS DO ARAGUAIA', 'CECOMT DO ARAGUAIA', 'REG', 'CONCEICAO DO ARAGUAIA'),
(30, 'UNID DE EXEC DE CONTR MERC EM TRANS BARREIRA DO CAMPO / CECOMT DO ARAGUAIA', 'CECOMT DO ARAGUAIA', 'REG', 'CONCEICAO DO ARAGUAIA'),
(31, 'UNID DE EXEC DE CONTR MERC EM TRANS Araguaia / CECOMT DO ARAGUAIA', 'CECOMT DO ARAGUAIA', 'REG', 'CONCEICAO DO ARAGUAIA'),
(32, 'COORD EXEC DE CONTR DE MERC EM TRANS DO GURUPI', 'CECOMT DO GURUPI', 'REG', 'CACHOEIRA DO PIRIA'),
(33, 'COORD EXEC DE CONTR DE MERC INTRANSITO DO ITINGA', 'CECOMT DO ITINGA', 'REG', 'DOM ELISEU'),
(34, 'COORD EXEC DE CONTR DE MERC TRANS DO TAPAJOS', 'CECOMT DO TAPAJOS', 'REG', 'OBIDOS'),
(35, 'COORD EXEC ESP DE ADM TRIBUT DE GRANDES CONTRIBUINTES', 'CEEAT - GC', 'REG', 'BELEM'),
(36, 'COORD EXEC ESP DE ADM TRIBUTARIA DO IPVA E DO ITCD', 'CEEAT - IPVA / ITCD', 'REG', 'BELEM'),
(37, 'COORD EXEC ESP DE ADM TRIBUT DE MICROS E PEQUENAS EMPRESAS', 'CEEAT - MPE', 'REG', 'BELEM'),
(38, 'COORD EXEC ESP DE ADM TRIBUT DE SUBST TRIBUTARIA', 'CEEAT - ST', 'REG', 'BELEM'),
(39, 'MOJU / CERAT DE ABAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'MOJU'),
(40, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE BAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'ABAETETUBA'),
(41, 'BARCARENA / CERAT DE ABAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'BARCARENA'),
(42, 'ABAETETUBA / CERAT DE ABAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'ABAETETUBA'),
(43, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE ALTAMIRA', 'CERAT DE ALTAMIRA', 'REG', 'ALTAMIRA'),
(44, 'COORD EXEC REG DA ADM TRIBUT E NAO TRIBUT DE ANANINDEUA', 'CERAT DE ANANINDEUA', 'REG', 'ANANINDEUA'),
(45, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE BELEM ', 'CERAT DE BELEM', 'REG', 'BELEM'),
(46, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE BREVES', 'CERAT DE BREVES', 'REG', 'BREVES'),
(47, 'PORTEL / CERAT DE BREVES', 'CERAT DE BREVES', 'REG', 'PORTEL'),
(48, 'SALINOPOLIS / CERAT DE CAPANEMA', 'CERAT DE CAPANEMA', 'REG', 'SALINOPOLIS'),
(49, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE CAPANEMA', 'CERAT DE CAPANEMA', 'REG', 'CAPANEMA'),
(50, 'BRAGANÇA / CERAT DE CAPANEMA', 'CERAT DE CAPANEMA', 'REG', 'BRAGANCA'),
(51, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE CAPANEMA', 'CERAT DE CAPANEMA', 'REG', 'BELEM'),
(52, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE CASTANHAL', 'CERAT DE CASTANHAL', 'REG', 'CASTANHAL'),
(53, 'CASTANHAL / CERAT DE CASTANHAL', 'CERAT DE CASTANHAL', 'REG', 'CASTANHAL'),
(54, 'ORGAO DE EXECUCAO DA ADM TRIBUT E NAO TRIBUTARIA / CERAT DE CASTANHAL', 'CERAT DE CASTANHAL', 'REG', 'CASTANHAL'),
(55, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE MARABA', 'CERAT DE MARABA', 'REG', 'MARABA'),
(56, 'ORGAO DE EXECUCAO DA ADM TRIBUT E NAO TRIBUTARIA / CERAT DE MARABA', 'CERAT DE MARABA', 'REG', 'MARABA'),
(57, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE PARAGOMINAS', 'CERAT DE PARAGOMINAS', 'REG', 'PARAGOMINAS'),
(58, 'ULIANOPOLIS / CERAT DE PARAGOMINAS', 'CERAT DE PARAGOMINAS', 'REG', 'ULIANOPOLIS'),
(59, 'ORGAO DE EXECUCAO DA ADM TRIBUT E NÃO TRIBUTARIA / CERAT DE PARAGOMINAS', 'CERAT DE PARAGOMINAS', 'REG', 'PARAGOMINAS'),
(60, 'MAE DO RIO / CERAT DE PARAGOMINAS', 'CERAT DE PARAGOMINAS', 'REG', 'MAE DO RIO'),
(61, 'REDENCAO / CERAT DE REDENCAO', 'CERAT DE REDENCAO', 'REG', 'REDENCAO'),
(62, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE REDENCAO', 'CERAT DE REDENCAO', 'REG', 'REDENCAO'),
(63, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE SANTAREM', 'CERAT DE SANTAREM', 'REG', 'SANTAREM'),
(64, 'MONTE ALEGRE / CERAT DE SANTAREM', 'CERAT DE SANTAREM', 'REG', 'MONTE ALEGRE'),
(65, 'ITAITUBA / CERAT DE SANTAREM', 'CERAT DE SANTAREM', 'REG', 'ITAITUBA'),
(66, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE TUCURUI', 'CERAT DE TUCURUI', 'REG', 'TUCURUI'),
(67, 'TAILANDIA / CERAT DE TUCURUI', 'CERAT DE TUCURUI', 'REG', 'TAILANDIA'),
(68, 'CORREGEDORIA FAZENDARIA', 'COFAZ', 'OC', 'BELEM'),
(69, 'CORREGEDORIA FAZENDARIA', 'COFAZ', 'REG', 'BELEM'),
(70, 'CONSULTORIA JURIDICA', 'CONJUR', 'REG', 'BELEM'),
(71, 'CONSULTORIA JURIDICA', 'CONJUR', 'OC', 'BELEM'),
(72, 'DIRETORIA DE AMBIENTE ANALÍTICO', 'DAA', 'OC', 'BELEM'),
(73, 'DIRETORIA DE ADMINISTRACAO - GABINETE', 'DAD', 'OC', 'BELEM'),
(74, 'CELULA DE GESTAO DE RECURSOS MATERIAIS - CGRM / DAD', 'DAD', 'OC', 'BELEM'),
(75, 'CELULA DE GESTAO DE PESSOAS - CGPE / DAD', 'DAD', 'OC', 'BELEM'),
(76, 'CELULA DE GESTAO DE LICITACOES E CONTRATOS - CGLC / DAD', 'DAD', 'OC', 'BELEM'),
(77, 'CELULA DE GESTAO DE RECURSOS FINANCEIROS - CGRF / DAD', 'DAD', 'OC', 'BELEM'),
(78, 'CELULA DE GESTAO DE APOIO LOGISTICO - CGAL / DAD', 'DAD', 'OC', 'BELEM'),
(79, 'CELULA DE ANALISE E CONTROLE DAS OBRIGACOES PRINCIPAIS - CCOP / DAIF', 'DAIF', 'OC', 'BELEM'),
(80, 'CELULA DE CONTROLE E COBRANCA DA DIVIDA ATIVA - CCDA / DAIF', 'DAIF', 'OC', 'BELEM'),
(81, 'CELULA DE INFORMACOES ECONOMICO FISCAIS - CIEF / DAIF', 'DAIF', 'OC', 'BELEM'),
(82, 'DIRETORIA DE ARRECADACAO E INFORMACOES FAZENDARIAS', 'DAIF', 'OC', 'BELEM'),
(83, 'CELULA DE ANALISE E CONTROLE DAS OBRIGAÇÕES ACESSORIAIS - CCOA / DAIF', 'DAIF', 'OC', 'BELEM'),
(84, 'DIRETORIA DE CREDITO TRIBUTARIO', 'DCT', 'OC', 'BELEM'),
(85, 'CELULA DE AVALIAÇÃO E CONTROLE DE AUTOMAÇÃO FISCAL / DFI', 'DFI', 'OC', 'BELEM'),
(86, 'CELULA DE PLANEJ MONITORAM E ESTUD TEC DE FISCALIZ- CPME / DFI', 'DFI', 'OC', 'BELEM'),
(87, 'CELULA DE PADRONIZACAO DE PROCED DE FISCALIZACAO - CPPF / DFI', 'DFI', 'OC', 'BELEM'),
(88, 'DIRETORIA DE FISCALIZACAO - GABINETE', 'DFI', 'OC', 'BELEM'),
(89, 'CELULA DE PROGRAM AVAL E CONTR DAS ACOES FISCAIS - CPCF / DFI', 'DFI', 'OC', 'BELEM'),
(90, 'CENTRAL DE MONITORAMENTO E OPERAÇÕES DE TRÂNSITO - CeMOTran / DFI', 'DFI - CeMOTran', 'OC', 'BELEM'),
(91, 'DIRETORIA DE TECNOLOGIA DA INFORMACAO', 'DTI', 'OC', 'BELEM'),
(92, 'CELULA DE GESTAO DE DADOS - CGDA / DTI', 'DTI', 'REG', 'BELEM'),
(93, 'DIRETORIA DE TECNOLOGIA DA INFORMAÇÃO', 'DTI', 'OC', 'BELEM'),
(94, 'CELULA DE GESTAO DE REDES - CGRE / DTI', 'DTI', 'OC', 'BELEM'),
(95, 'CELULA DE ANALISE E ACOMP DOS INCENT E BENEF FISC - CAIF / DTR', 'DTR', 'OC', 'BELEM'),
(96, 'DIRETORIA DE TRIBUTACAO', 'DTR', 'OC', 'BELEM'),
(97, 'CELULA DE CONSULTA E ORIENTACAO TRIBUTARIA - CCOT / DTR', 'DTR', 'OC', 'BELEM'),
(98, 'DIRETORIA DE TRIBUTAÇÃO', 'DTR', 'OC', 'BELEM'),
(99, 'CELULA DE DESENVOLVIMENTO ESTRATEGICO - CDE / EFAZ', 'EFAZ', 'REG', 'BELEM'),
(100, 'ESCOLA FAZENDARIA', 'EFAZ', 'REG', 'BELEM'),
(101, 'GABINETE DO SECRETARIO', 'GAB-SEC', 'OC', 'BELEM'),
(102, 'JULGADORIA DE PRIMEIRA INSTANCIA ', 'JULGADORIA', 'REG', 'BELEM'),
(103, 'CELULA DE PROGRAMACAO E EXECUCAO FINANCEIRA - COFI / DITES / SAT', 'SAT', 'OC', 'BELEM'),
(104, 'CELULA DE CAPTACAO RECURSOS CONTROLE DA DIVIDA - COEN / DITES / SAT', 'SAT', 'OC', 'BELEM'),
(105, 'CELULA DO SISTEMA INTEGRADO ADM FINANCEIRA ESTADUAL - CSFE / DICONF / SAT', 'SAT', 'OC', 'BELEM'),
(106, 'DIRETORIA DE GESTAO CONTABIL E FISCAL - DICONF / SAT', 'SAT', 'OC', 'BELEM'),
(107, 'unassigned', 'SAT', 'OC', 'BELEM'),
(108, 'SECRETARIA ADJUNTA DO TESOURO', 'SAT', 'OC', 'BELEM'),
(109, 'CELULA DE CONTABILIDADE - CCONT / DICONF / SAT', 'SAT', 'OC', 'BELEM'),
(110, 'CELULA FISCAL - CFIS / DICONF / SAT', 'SAT', 'OC', 'BELEM'),
(111, 'SUBSECRETARIO DA ADMINISTRAÇAO TRIBUTARIA', 'SSAT', 'OC', 'BELEM'),
(112, 'TRIBUNAL ADMINISTRATIVO DE RECURSOS FAZENDARIOS', 'TARF', 'REG', 'BELEM'),
(113, 'UNIDADE DE CONTROLE INTERNO ', 'UCI', 'OC', 'BELEM'),
(115, 'DIRETORIA DO TESOURO ESTADUAL- DITES / SAT', 'SAT', 'OC', 'BELEM'),
(116, 'CAMETA / CERAT DE ABAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'CAMETA'),
(117, 'GOIANESIA DO PARA / CERAT DE TUCURUI', 'CERAT DE TUCURUI', 'REG', 'GOIANESIA DO PARA'),
(118, 'DICIPLINA E ETICA / COFAZ', 'COFAZ', 'OC', 'BELEM'),
(119, 'XINGUARA / CERAT DE REDENCAO', 'CERAT DE REDENCAO', 'REG', 'XINGUARA'),
(120, 'CELULA DE GESTAO DE PROJETOS E SISTEMAS - CGPS / DTI', 'DTI', 'OC', 'BELEM'),
(121, 'CELULA DE ANALISE E ELABORACAO DE NORMAS - CAEN / DTR', 'DTR', 'OC', 'BELEM'),
(122, 'ASSISTENCIA TECNICA - ASTEC / DFI', 'DFI', 'OC', 'BELEM'),
(123, 'CELULA DE ANALISE E CONTROLE DA ARRECACAO - CACA / DAIF', 'DAIF', 'OC', 'BELEM'),
(124, 'COORD EXEC DE CONTR DE MERC TRANS DE PORTOS E AEROPORTOS', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'luisa'),
(125, 'UNID DE EXEC DE CONTR MERC EM TRANS DA GRANDE BELEM / CECOMT', 'CECOMT', 'REG', 'SAO FRANCISCO DO'),
(126, 'ORGAO DE EXECUCAO DA ADM TRIBUT E NAO TRIBUTARIA / CERAT DE ABAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'ABAETETUBA'),
(127, 'AFUA / CERAT DE BREVES', 'CERAT DE BREVES', 'REG', 'AFUA'),
(128, 'VIGIA / CERAT DE CASTANHAL', 'CERAT DE CASTANHAL', 'REG', 'VIGIA'),
(129, 'CORREIÇÃO / COFAZ', 'COFAZ', 'OC', 'BELEM'),
(130, 'UNID DE EXEC DE CONTR MERC EM TRANS CURRALINHO / CECOMT', 'CECOMT', 'REG', 'CURRALINHO'),
(131, 'CELULA DE PADRONIZACAO DE PROCED DE FISCALIZACAO - CPPF / DFI', 'DFI', 'REG', 'BELEM'),
(132, 'ORGAO DE EXECUCAO DA ADM TRIBUT E NAO TRIBUTARIA / CERAT DE TUCURUI', 'CERAT DE TUCURUI', 'REG', 'TUCURUI'),
(133, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE ALTAMIRA', 'CERAT DE ALTAMIRA', 'REG', 'ALTAMIRA/ Remover por 1 ano '),
(134, 'BREU BRANCO / CERAT DE TUCURUI', 'CERAT DE TUCURUI', 'REG', 'BREU BRANCO'),
(135, 'IGARAPE MIRI / CERAT DE ABAETETUBA', 'CERAT DE ABAETETUBA', 'REG', 'IGARAPE MIRI'),
(136, 'UNID DE EXEC DE CONTR MERC EM TRANS DE MIRAMAR / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(137, 'CELULA DE COORDENACAO DO PLANEJAMENTO ESTRATEGICO - CPE / CAFE', 'CAFE', 'OC', 'BELEM'),
(138, 'CÉLULA DA QUALIDADE DO CRÉDITO -DCT', 'DCT', 'OC', 'BELEM'),
(139, 'SECRETARIO ADJUNTO DO TESOURO', 'SAT', 'OC', 'BELEM'),
(140, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE PARAGOMINAS', 'CERAT DE ANANINDEUA', 'REG', 'ANANINDEUA'),
(141, 'TUCUMA / CERAT DE REDENCAO', 'CERAT DE REDENCAO', 'REG', 'TUCUMA'),
(142, 'COORD EXEC DE CONTROLE DE MERCADORIAS EM TRANSITO', 'CECOMT ', 'REG', 'BELEM'),
(143, 'UNID DE EXEC DE CONTR MERC EM TRANSITO DA CEASA / CECOMT', 'CECOMT', 'REG', 'BELEM'),
(144, 'SAO MIGUEL DO GUAMA / CERAT DE CASTANHAL', 'CERAT DE CASTANHAL', 'REG', 'SAO MIGUEL DO GUA'),
(145, 'OUVIDORIA FAZENDARIA', 'OUVIDORIA', 'OC', 'BELEM'),
(146, 'UNID DE EXEC CONTR MERC TRANS CARNE DE SOL / CECOMT DE CARAJAS', 'CECOMT DE CARAJAS', 'REG', 'ABEL FIGUEIREDO'),
(147, 'COORDNADORIA DE ASSUNTOS FAZENDARIOS ESTRATEGICOS', 'CAFE', 'REG', 'BELEM'),
(148, 'ORGAO DE EXECUCAO DA ADM TRIBUT E NÃO TRIBUTARIA / CERAT DE SANTAREM', 'CERAT DE SANTAREM', 'REG', 'SANTAREM'),
(149, 'CELULA DE GESTAO DE PROJETOS E SISTEMAS - CGPS / DTI', 'DTI', 'REG', 'BELEM'),
(150, 'CAPITAO POCO / CERAT DE PARAGOMINAS', 'CERAT DE PARAGOMINAS', 'REG', 'CAPITAO POCO'),
(151, 'MEDICILANDIA / CERAT DE ALTAMIRA', 'CERAT DE ALTAMIRA', 'REG', 'MEDICILANDIA'),
(152, 'PARAGOMINAS / CERAT DE PARAGOMINAS', 'CERAT DE PARAGOMINAS', 'REG', 'PARAGOMINAS'),
(153, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE CASTANHAL', 'CERAT DE PARAGOMINAS', 'REG', 'PARAGOMINAS'),
(154, 'ANAJAS / CERAT DE BREVES', 'CERAT DE BREVES', 'REG', 'ANAJAS'),
(155, 'COORD EXEC REG DE ADM TRIBUT E NAO TRIBUT DE CAPANEMA', 'CERAT DE CAPANEMA', 'REG', 'CASTANHAL'),
(156, 'CELULA DE SISTEMATIZACAO DE ATOS NORMATIVOS - CSAN / DTR', 'DTR', 'OC', 'BELEM'),
(157, 'UNID DE EXEC DE CONTR MERC EM TRANS DE SANTAREM / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM'),
(158, 'CÉLULA DE ATENDIMENTO', 'DAD', 'OC', 'BELEM'),
(159, 'RONDON / CERAT DE MARABA', 'CERAT DE MARABA', 'REG', 'MARABA'),
(160, 'UNID DE EXEC de CONTR MERC EM TRANS PORTO DER / CECOMT DE P. AEROP.', 'CECOMT DE PORTOS E AEROPORTOS', 'REG', 'BELEM');
